version: '3.8'

services:
  db:
    image: postgres:15
    container_name: soporte-db
    environment:
      POSTGRES_DB: supportdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: soporte-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/supportdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - soporte-network

volumes:
  db_data:

networks:
  soporte-network:
    driver: bridge
