spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supportdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # :contentReference[oaicite:0]{index=0}

jwt:
  secret: MiSuperSecretoParaJWTQueDebeSerMuyLargoYSeguro123!
  expirationMs: 3600000
